export const cartLocators = {
  cart: '.shopping_cart_link',
  cartItem: '.cart_item',
  cartQuantity: '.cart_quantity',
  cartItemName: '.inventory_item_name',
  cartItemDescription: '.inventory_item_desc',
  cartItemPrice: '.inventory_item_price',
  removeButton: '[data-test^="remove-"]',
  continueShoppingButton: '[data-test="continue-shopping"]',
  checkoutButton: '[data-test="checkout"]',
  firstNameInput: '#first-name',
  lastNameInput: '#last-name',
  postalCodeInput: '#postal-code',
  continueButton: '[data-test="continue"]',
  cancelButton: '[data-test="cancel"]',
  finishButton: '[data-test="finish"]',
  subtotalLabel: '.summary_subtotal_label',
  taxLabel: '.summary_tax_label',
  totalLabel: '.summary_total_label',
  completeHeader: '.complete-header',
  errorMessage: '[data-test="error"]'
};
